package main;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.mindrot.jbcrypt.BCrypt;
/**
 *
 * @author Phomane
 */
public class Signup extends javax.swing.JFrame {

public String hashed = "",
        slt = ""; 
    
    public Signup() {
        initComponents();
        //signup.EXIT_ON_CLOSE
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        signUp = new javax.swing.JButton();
        passw = new javax.swing.JPasswordField();
        passwd = new javax.swing.JPasswordField();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sign Up");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 150, 60);

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel1.add(uname);
        uname.setBounds(240, 110, 200, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Username");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 80, 60, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 150, 70, 17);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Comfirm Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 220, 140, 17);

        signUp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        signUp.setForeground(new java.awt.Color(153, 153, 153));
        signUp.setText("Sign Up");
        signUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        jPanel1.add(signUp);
        signUp.setBounds(240, 300, 90, 25);
        jPanel1.add(passw);
        passw.setBounds(240, 180, 200, 30);
        jPanel1.add(passwd);
        passwd.setBounds(240, 250, 200, 30);

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/register.png"))); // NOI18N
        jPanel1.add(pic);
        pic.setBounds(10, 80, 220, 250);
        //ImageIcon icon = new ImageIcon("/images/register.png");
        //pic.setIcon(icon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(476, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // TODO add your handling code here:
        UserDatabase db = new UserDatabase();
        String nam = uname.getText().trim();
        String pass = passw.getText().trim();
        String passl = passwd.getText().trim();
           
        if(pass.equals(passl))
        {
            try{
            db.connect();
            if (db.checkUser(nam, pass))
            {
                JOptionPane.showMessageDialog(null, "Username exists, try different name!");
                uname.setText("");
                passw.setText("");
                passwd.setText("");
            }
            else {
              slt = BCrypt.gensalt();
                hashed = hashPassword(pass,slt);
                db.insertUser(new User(nam,hashed,slt));
                this.dispose();
                new Login().setVisible(true);
            }           
        }
       
        catch(Exception ex){
            
        }
     }
        else
            JOptionPane.showMessageDialog(null, " Password mismatch please try agaiin!");
        
    }//GEN-LAST:event_signUpActionPerformed

   public String hashPassword(String plainTextPassword,String salt){
    return BCrypt.hashpw(plainTextPassword, salt);
}
        
    /**  
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, UnsupportedLookAndFeelException, InstantiationException {
        /* Set the Nimbus look and feel */
      
       /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      */
UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passw;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JLabel pic;
    private javax.swing.JButton signUp;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
